# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e27a078bcf8a69f48808a7f602042e18d7ffec3d4c32bf8ad63c467f0fa9e4bd0dfc1f265a7ae8c0ed44ca98006a2869fd5a6010e062e71f3ce1a29d1ea701a

test:
  secret_key_base: 492372a6ec1a44b6ecbbe74ee018f550565551340d4ed94d227a4ec676b2da87b26a345ff2f6f348909c24122f9d86855abaab64cf34b9399ec99e72ed5320d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
